package com.pockettravel.core.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource

// Unico set di icone dell'app: Material Symbols Rounded (peso 400, griglia 24 dp), vector
// drawable ufficiali copiati da github.com/google/material-design-icons (symbols/android/<nome>/
// materialsymbolsrounded/, attributo tint rimosso: la tinta la applica Icon). Nessuna dipendenza
// da material-icons-extended. Le varianti *Filled (fill 1) sono per gli elementi selezionati
// della navigazione, come prevede M3.
object AppIcons {
    val Back: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_arrow_back)
    val Menu: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_menu)
    val Add: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_add)
    val Close: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_close)
    val Send: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_send)
    val Refresh: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_refresh)
    val Search: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_search)
    val ExpandMore: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_expand_more)
    val ListView: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_list)
    val Check: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_check)
    val Error: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_error)
    val Delete: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_delete)
    val Edit: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_edit)
    val Lock: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_lock)
    val OpenExternal: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_open_in_new)
    val Download: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_download)
    val Favorite: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_favorite)
    val Help: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_help)
    val Info: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_info)
    val Settings: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_settings)
    val Palette: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_palette)
    val World: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_public)
    val WorldFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_public_fill)
    val Compass: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_explore)
    val CompassFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_explore_fill)
    val Map: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_map)
    val MapFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_map_fill)
    val AiAssistant: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_auto_awesome)
    val AiAssistantFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_auto_awesome_fill)
    val Documents: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_description)
    val DocumentsFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_description_fill)
    val More: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_more_horiz)
    val MoreFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_more_horiz_fill)
    val Storage: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_storage)
    val Licenses: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_gavel)
    val Tutorial: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_school)
    val Camera: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_photo_camera)
    val Checklist: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_checklist)
    val Flights: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_flight)
    val HealthGuidance: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_health_and_safety)
    val Emergency: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_emergency)
    val Call: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_call)
    val OfficialAuthority: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_account_balance)
    val OfflineWifi: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_wifi_off)
    val Translation: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_translate)
    val VerifiedLink: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_verified_user)
    val Accommodation: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_hotel)
    val FoodDrink: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_restaurant)
    val Shopping: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_shopping_bag)
    val Attractions: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_attractions)
    val Place: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_location_on)
    val Route: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_route)
    val Book: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_menu_book)
    val MoreVert: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_more_vert)
    val Connectivity: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_wifi)
    val DailyLife: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_home)
    val Customs: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_fact_check)
    val Passport: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_badge)
    val Vaccinations: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_vaccines)
}
